name: Auto-reply to new issues

on:
  issues:
    types: [opened]

jobs:
  auto_reply:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-reply to new issues
      uses: cj-mills/auto-reply-workflow@main
       with:
         issue-comment: "Thank you for your issue! Our team will review it and get back to you shortly."