name: Auto Reply to Issues

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Auto reply to issue
      uses: actions-ecosystem/auto-reply@v1.2.0
      with:
        issue-number: ${{ github.event.issue.number }}
        repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
        comment: "Thank you for opening this issue. We will look into it as soon as possible."